config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  get 'youkos/dog' => 'youkos#dog'
  get 'youkos/cat' => 'youkos#cat'
  get 'youkos/hadakadebanezumi' => 'youkos#hadakadebanezumi'
 
 
  resources :youkos
  root 'youkos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/youko.rb
class Youko < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/youkos_controller.rb
class YoukosController < ApplicationController


    def index
        @youkos = Youko.all
        @youkos = @youkos.page(params[:page]).per(3)
    end


    def new
        @youko = Youko.new
     end
    
      def create
        youko = Youko.new(youko_params)
        if youko.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
    
      def dog
        @youkos = Youko.where(cause: "二日酔い")
      end
    
      def cat
        @youkos = Youko.where(cause: "夏バテ")
      end
    
      def hadakadebanezumi
        @youkos = Youko.where(cause: "貧血")
      end
    
      def edit
        @youko = Youko.find(params[:id])
      end

      def update
        youko = Youko.find(params[:id])
        if youko.update(youko_params)
          redirect_to :action => "show", :id => youko.id
        else
          redirect_to :action => "new"
        end
      end


        def show
          @youkos = Youko.find(params[:id])
        end
     

      private
      def youko_params
        params.require(:youko).permit(:food, :effect, :cook, :cause, :image)
        
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/youkos_helper.rb
module YoukosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eiyouso</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/youkos/cat.html.erb
<h1>夏バテのキモチ</h1>
<% @youkos.each do |t| %>
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <%= t.food %>
    <%= t.effect %>
    <%= t.cook %>
    <%= t.cause %>
<% end %>

app/views/youkos/dog.html.erb
<h1>二日酔いのキモチ</h1>
<% @youkos.each do |t| %>
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <%= t.food %>
    <%= t.effect %>
    <%= t.cook %>
    <%= t.cause %>
<% end %>

app/views/youkos/edit.html.erb
<%= form_for @youko do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/youkos/hadakadebanezumi.html.erb
<h1>貧血のキモチ</h1>
<% @youkos.each do |t| %>
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <%= t.food %>
    <%= t.effect %>
    <%= t.cook %>
    <%= t.cause %>
<% end %>

app/views/youkos/index.html.erb
<h1>youko</h1>
<h3>一覧ページ</h3>
<%= link_to "新規投稿へ", new_youko_path %>
<%= link_to "cat", youkos_dog_path %>
<%= link_to "dog", youkos_cat_path %>
<%= link_to "hadakadebanezumi", youkos_hadakadebanezumi_path %>

<%= page_entries_info @youkos %>
<%= paginate @youkos %>

<div class="youko-container">

  <% @youkos.each do |t| %>
    <%= link_to "詳細へ", youko_path(t.id) %>

    <div class="youko">
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <%= t.food %>
      <%= t.effect %>
      <%= t.cook %>
      <%= t.cause %>
    </div>
  <% end %>
</div>

app/views/youkos/new.html.erb
<h1>(youko)</h1>
<h3>新規投稿ページ</h3>
<%= form_for @youko do |f| %>

# データ型がstringで自由記述の入力フォーム
  <div class="field">
    <%= f.label :食品 %>
    <%= f.text_field :food, :size => 30 %>
  </div>

# データ型がstringで選択式の入力フォーム
  <div class="field">
    <%= f.label :原因 %>
    <%= f.select :cause, 
    [["二日酔い", "二日酔い"], 
    ["貧血", "貧血"], 
    ["夏バテ", "夏バテ"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
    <%= f.label :効果 %>
    <%= f.text_field :effect, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :料理 %>
    <%= f.text_field :cook, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  

  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", youkos_path %>

app/views/youkos/show.html.erb

<h1>GeekTwitter</h1>
<h3>Tweet詳細</h3>
<div class="youko">
  <p><%= @youkos.food %></p>
  <p><%= @youkos.created_at %></p>
</div>

<%= link_to "Tweet一覧に戻る", youkos_path %>